# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-6lK_RU7P6XMQ8aZsYy2lhxfrEnq4B8
"""

from .revnet import VGG, RevBlock, RevBlockFunction 
def VGG20():
    model = VGG(
            units=[1,1,1,1,1],
            filters=[64,64,128,256,512,512],
            strides=[1, 1, 1,1,1],
            classes=10
            )
    model.name = "VGG"
    return model